Re-enable unit tests in CI.
Now that we have some unit tests for at least some of the code base,
let's turn unit tests back on in CI.

Signed-off-by: Michael Still <mikal@stillhq.com>

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -67,48 +67,48 @@ jobs:
           pip3 install uv
           uv pip install -r pyproject.toml
 
-      # - name: Run python3 unit tests
-      #   timeout-minutes: 10
-      #   run: |
-      #     . /tmp/venv-test/bin/activate
-      #     tox -epy3
+      - name: Run python3 unit tests
+        timeout-minutes: 10
+        run: |
+          . /tmp/venv-test/bin/activate
+          tox -epy3
 
-      # - name: List failing tests
-      #   if: failure()
-      #   id: failures
-      #   run: |
-      #     echo "Gathering list of failed tests..."
-      #     touch /srv/ci/failed
-      #     . /tmp/venv-test/bin/activate
-      #     tox -efailing || true > /srv/ci/failed
-      #     echo
+      - name: List failing tests
+        if: failure()
+        id: failures
+        run: |
+          echo "Gathering list of failed tests..."
+          touch /srv/ci/failed
+          . /tmp/venv-test/bin/activate
+          tox -efailing || true > /srv/ci/failed
+          echo
 
-      #     failed=$(cat /srv/ci/failed | egrep "^FAIL: " | \
-      #         sed -z 's/FAIL: shakenfist_ci\.//g;s/\n/, /g;s/, $/\n/')
+          failed=$(cat /srv/ci/failed | egrep "^FAIL: " | \
+              sed -z 's/FAIL: shakenfist_ci\.//g;s/\n/, /g;s/, $/\n/')
 
-      #     echo "Failed tests:"
-      #     cat /srv/ci/failed
-      #     echo
+          echo "Failed tests:"
+          cat /srv/ci/failed
+          echo
 
-      #     echo "failures<<EOF" >> ${GITHUB_OUTPUT}
-      #     echo "${failed}" >> ${GITHUB_OUTPUT}
-      #     echo "EOF" >> ${GITHUB_OUTPUT}
-      #     echo "GITHUB_OUTPUT is:"
-      #     cat ${GITHUB_OUTPUT}
+          echo "failures<<EOF" >> ${GITHUB_OUTPUT}
+          echo "${failed}" >> ${GITHUB_OUTPUT}
+          echo "EOF" >> ${GITHUB_OUTPUT}
+          echo "GITHUB_OUTPUT is:"
+          cat ${GITHUB_OUTPUT}
 
-      # - name: Generate coverage report
-      #   timeout-minutes: 10
-      #   run: |
-      #     . /tmp/venv-test/bin/activate
-      #     tox -ecover
-      #     zip -r cover.zip cover
+      - name: Generate coverage report
+        timeout-minutes: 10
+        run: |
+          . /tmp/venv-test/bin/activate
+          tox -ecover
+          zip -r cover.zip cover
 
-      # - uses: actions/upload-artifact@v4
-      #   with:
-      #     name: coverage
-      #     retention-days: 90
-      #     if-no-files-found: error
-      #     path: cover.zip
+      - uses: actions/upload-artifact@v4
+        with:
+          name: coverage
+          retention-days: 90
+          if-no-files-found: error
+          path: cover.zip
 
   ovirt_matrix:
     name: "${{ matrix.test.description }}"
