Perform sanity checks.

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -22,6 +22,79 @@ on:
       - develop
 
 jobs:
+  sanity_checks:
+    runs-on: [self-hosted, vm]
+    concurrency:
+      group: ${{ github.workflow }}-${{ github.ref }}-lint
+      cancel-in-progress: true
+
+    steps:
+      - name: Checkout code with two commits
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 2
+
+      - name: Install additional dependencies not tracked by pip
+        timeout-minutes: 5
+        run: |
+          python3 -mvenv /tmp/bindep-venv
+          /tmp/bindep-venv/bin/pip3 install bindep
+          echo
+          /tmp/bindep-venv/bin/bindep || true
+          echo
+          sudo apt-get install -y $(/tmp/bindep-venv/bin/bindep --brief || true)
+
+      - name: Lint with flake8
+        timeout-minutes: 5
+        run: |
+          /usr/bin/tox -eflake8
+
+      - name: Attempt to install requirements
+        timeout-minutes: 5
+        run: |
+          python3 -mvenv /tmp/venv
+          /tmp/venv/bin/pip3 install -r requirements.txt
+
+      - name: Run python3 unit tests
+        timeout-minutes: 10
+        run: |
+          /usr/bin/tox -epy3
+
+      - name: List failing tests
+        if: failure()
+        id: failures
+        run: |
+          echo "Gathering list of failed tests..."
+          touch ${GITHUB_WORKSPACE}/failed
+          /usr/bin/tox -efailing || true > ${GITHUB_WORKSPACE}/failed
+          echo
+
+          failed=$(cat ${GITHUB_WORKSPACE}/failed | egrep "^FAIL: " | \
+              sed -z 's/FAIL: shakenfist_ci\.//g;s/\n/, /g;s/, $/\n/')
+
+          echo "Failed tests:"
+          cat ${GITHUB_WORKSPACE}/failed
+          echo
+
+          echo "failures<<EOF" >> ${GITHUB_OUTPUT}
+          echo "${failed}" >> ${GITHUB_OUTPUT}
+          echo "EOF" >> ${GITHUB_OUTPUT}
+          echo "GITHUB_OUTPUT is:"
+          cat ${GITHUB_OUTPUT}
+
+      - name: Generate coverage report
+        timeout-minutes: 10
+        run: |
+          /usr/bin/tox -ecover
+          zip -r cover.zip cover
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: coverage
+          retention-days: 90
+          if-no-files-found: error
+          path: cover.zip
+
   functional_matrix:
     name: "${{ matrix.test.description }}"
     strategy:
@@ -51,6 +124,7 @@ jobs:
           },
         ]
     runs-on: [self-hosted, vm]
+    needs: sanity_checks
     timeout-minutes: 120
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test.name }}
